### PR TITLE
Mysql setup

### PR DESCRIPTION
**Pull request by zaach**
This will set up mysql on new deployments.

### CODE REVIEW

**Comment by rfk** [comment]
Looks like this failed in travis - I'll try to take a look later today if @zaach doesn't beat me to it.

**Comment by zaach** [comment]
Hmm, I'll rebase and update the PR.

**Comment by rfk** [comment]
Not sure what's up with travis, but I don't see how this code could possibly be causing the problem.  So, merging.

**Comment by zaach** [comment]
You know, we can probably remove couchbase as a database option for now. I'll remove the install in a separate PR.

**Pull request merged**
